<?php
    function favorites_menu() {
        $items = array();

        $items['add/favorites/%'] = array(
            'page callback' => 'favorites_add',
            'type' => MENU_CALLBACK,
            'access arguments' => array('access content'),
            'page arguments' => array(2)
        );


        $items['delete/favorites/%'] = array(
            'page callback' => 'favorites_delete',
            'type' => MENU_CALLBACK,
            'access arguments' => array('access content'),
            'page arguments' => array(2)
        );


        return $items;
    }

    function favorites_theme($existing, $type, $theme, $path){
        return array(
            'add_auth_favorite' => array(
                'template' => 'templates/add_auth',
            ),
            'delete_auth_favorite' => array(
                'template' => 'templates/delete_auth',
            )
            
        );
    }

     

    function favorites_add($nid){
        if (!preg_match('/^[0-9]+$/', $nid)) {
            drupal_not_found();
            drupal_exit();
        }
        $node = node_load($nid);
        if (!$node) {
            drupal_not_found();
            drupal_exit();
        }
        
        global $user;
        $participant = (int) db_select('favorites', 'a')
            ->condition('uid', $user->uid)
            ->condition('nid', $node->nid)
            ->countQuery()
            ->execute()
            ->fetchField();
        if ($participant > 0) {
            drupal_not_found();
            drupal_exit();
        }
        db_insert('favorites')
            ->fields(array('uid' => $user->uid, 'nid' => $node->nid))
            ->execute();
        
        #drupal_set_message('Добавлено в избранное', 'status');
        
        drupal_goto(drupal_get_path_alias('node/'.$node->nid));
    }


    function favorites_delete($nid) {
        if (!preg_match('/^[0-9]+$/', $nid)) {
            drupal_not_found();
            drupal_exit();
        }
        global $user;
        $node = node_load($nid);
       
        if (!$node) {
            drupal_not_found();
            drupal_exit();
        }

        db_delete('favorites')
            ->condition('uid', $user->uid)
            ->condition('nid', $nid)
            ->execute();
        //drupal_set_message('Удалено из избранного.', 'status');
        drupal_goto(drupal_get_path_alias('/node/'.$nid));
    }
    

    function favorites_node_view($node, $view_mode, $langcode) {  
        
        $node_type = $node->type;

        if ($node_type == 'lot' xor $node_type == 'tovar'){
            
            global $user;
            
            
            if (in_array('authenticated user', $user->roles)) {
            
                $participant = (int) db_select('favorites', 'a')
                    ->condition('uid', $user->uid)
                    ->condition('nid', $node->nid)
                    ->countQuery()
                    ->execute()
                    ->fetchField();
                if ($participant === 0) {
                    $node->content['favorite_button'] = array(
                        '#markup' => theme('add_auth_favorite', array('nid' => $node->nid)),
                        '#weight' => -1
                    
                    );
            
                    return true;
                }elseif($participant  > 0){

                    $node->content['favorite_button'] = array(
                        '#markup' => theme('delete_auth_favorite', array('nid' => $node->nid)),
                        '#weight' => -1
                    );

                    return true;
                }

                return true;
            };
        }
                    
        return true;
    }
       
